# Doesn't use in k8s only for local testing with nginx act as reverse proxy and load balancer

services:
  ingress: 
    image: nginx:alpine
    ports:
      - "9080:9080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - productpage
      - details
      - ratings
      - reviews

  productpage:
    build:
      context: ../src/productpage 
      dockerfile: Dockerfile
    image: productpage-service:v1
    environment:
      DETAILS_HOSTNAME: http://details:9080
      RATINGS_HOSTNAME: http://ratings:9080
      REVIEWS_HOSTNAME: http://reviews:9080
      FLOOD_FACTOR: 0
    hostname: productpage

  details:
    build:
      context: ../src/details
      dockerfile: Dockerfile
    image: details-service:v1
    hostname: details
    environment: 
      ENABLE_EXTERNAL_BOOK_SERVICE: false
      DO_NOT_ENCRYPT: false

  ratings:
    build:
      context: ../src/ratings
      dockerfile: Dockerfile
    image: ratings-service:v2
    hostname: ratings
    environment:
      SERVICE_VERSION: v2
      MONGO_DB_URL: mongodb://db:27017
      MONGO_DB_USERNAME: SOME_USERNAME
      MONGO_DB_PASSWORD: SOME_PASSWORD
      MONGO_DB_NAME: ratings
    depends_on:
      - db

  db:
    image: bitnami/mongodb:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGODB_ROOT_PASSWORD: SOME_PASSWORD
      MONGODB_USERNAME: SOME_USERNAME
      MONGODB_PASSWORD: SOME_PASSWORD
      MONGODB_DATABASE: ratings
    volumes:
      - ./src/ratings/databases:/docker-entrypoint-initdb.d

  reviews:
    build:
      context: ../src/reviews
      dockerfile: Dockerfile
    image: reviews-service:v1
    hostname: reviews
    environment:
      STAR_COLOR: black
      ENABLE_RATINGS: true
      RATINGS_SERVICE: http://ratings:9080
      HOSTNAME: reviews-service-1
      CLUSTER_NAME: cluster-1
    depends_on:
      - ratings
