architecture: standalone

auth:
  username: user1
  database: ratings
  
  existingSecret: mongodb-creds-dev

  passwordKey: mongodb-passwords       
  rootPasswordKey: mongodb-root-password
  userNameKey: db-username

initdbScriptsConfigMap: mongodb-init-script-dev

persistence:
  enabled: true
  size: 8Gi

extraEnvVars:
  - name: MONGODB_USERNAME
    valueFrom:
      secretKeyRef:
        name: mongodb-creds-dev
        key: db-username
  - name: MONGODB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mongodb-creds-dev
        key: mongodb-passwords
  - name: MONGODB_DATABASE
    value: "ratings"