architecture: standalone

auth:
  username: user1
  database: ratings

  existingSecret: mongodb-creds-prod

  passwordKey: mongodb-passwords      
  rootPasswordKey: mongodb-root-password
  
  userNameKey: db-username

initdbScriptsConfigMap: mongodb-init-script-prod

persistence:
  enabled: true
  size: 8Gi

extraEnvVars:
  - name: MONGODB_USERNAME
    valueFrom:
      secretKeyRef:
        name: mongodb-creds-prod
        key: db-username
  - name: MONGODB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mongodb-creds-prod
        key: mongodb-passwords
  - name: MONGODB_DATABASE
    value: "ratings"