apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-v1
  namespace: bookinfo-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: bitnami/mongodb:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGODB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-creds
              key: root-password
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-creds
              key: db-username
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-creds
              key: db-password
        - name: MONGODB_DATABASE
          value: "ratings"
        volumeMounts:
        - name: mongodb-data
          mountPath: /bitnami/mongodb
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mongodb-data
        emptyDir: {}
      - name: init-script
        configMap:
          name: mongodb-init-script