- op: replace
  path: /spec/rules/0/host
  value: bookinfo-supeem-dev.opsta.in.th

- op: add
  path: /spec/tls
  value:
    - hosts:
      - bookinfo-supeem-dev.opsta.in.th
      secretName: bookinfo-dev-tls

- op: add
  path: /metadata/annotations/cert-manager.io~1cluster-issuer
  value: "letsencrypt-prod"