apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookinfo-dev


resources:
- ../../base-app/database
- ../../base-app/ratings
- ../../base-app/reviews
- ../../base-app/details
- ../../base-app/productpage
- ../../base-app/ingress

patches:
- path: ingress-patch.yaml
  target:
    kind: Ingress
    name: bookinfo-ingress
    
labels:
- includeSelectors: true
  pairs:
    environment: dev
    project: bookinfo
